data = {
    "cityid": "101200101",
    "city": "武汉",
    "cityEn": "wuhan",
    "country": "中国",
    "countryEn": "China",
    "update_time": "2025-02-23 00:15:29",
    "data": [
        {
            "day": "23日（星期日）",
            "date": "2025-02-23",
            "week": "星期日",
            "wea": "雾",
            "wea_img": "wu",
            "wea_day": "小雨",
            "wea_day_img": "yu",
            "wea_night": "多云",
            "wea_night_img": "yun",
            "tem": "5.7",
            "tem1": "7",
            "tem2": "4",
            "humidity": "80%",
            "visibility": "4km",
            "pressure": "1032",
            "win": [
                "东北风",
                "无持续风向"
            ],
            "win_speed": "3-4级转<3级",
            "win_meter": "4km\/h",
            "sunrise": "06:56",
            "sunset": "18:16",
            "air": "97",
            "air_level": "良",
            "air_tips": "",
            "phrase": "小雨",
            "narrative": "小雨。 最高 8°C。 东北偏北 风，风向多变。 降雨几率 80%。",
            "moonrise": "02:19",
            "moonset": "12:13",
            "moonPhrase": "残月",
            "rain": "77",
            "uvIndex": "1",
            "uvDescription": "低",
            "rain_pcpn": "0.0",
            "alarm": []
        },
        {
            "day": "24日（星期一）",
            "date": "2025-02-24",
            "week": "星期一",
            "wea": "多云",
            "wea_img": "yun",
            "wea_day": "多云",
            "wea_day_img": "yun",
            "wea_night": "多云",
            "wea_night_img": "yun",
            "tem": "11",
            "tem1": "11",
            "tem2": "1",
            "humidity": "59%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:55",
            "sunset": "18:16",
            "air": "74",
            "air_level": "良",
            "air_tips": "",
            "phrase": "局部多云",
            "narrative": "少云。 最高 11°C。 东北偏北 风 10 到 15 每 km \/ h 。",
            "moonrise": "03:18",
            "moonset": "13:07",
            "moonPhrase": "残月",
            "rain": "6",
            "uvIndex": "5",
            "uvDescription": "中等",
            "rain_pcpn": "0.0"
        },
        {
            "day": "25日（星期二）",
            "date": "2025-02-25",
            "week": "星期二",
            "wea": "晴转小雨",
            "wea_img": "yu",
            "wea_day": "晴",
            "wea_day_img": "qing",
            "wea_night": "小雨",
            "wea_night_img": "yu",
            "tem": "10",
            "tem1": "10",
            "tem2": "2",
            "humidity": "56%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:54",
            "sunset": "18:17",
            "air": "52",
            "air_level": "良",
            "air_tips": "",
            "phrase": "大部分地区多云",
            "narrative": "大部多云。 最高 11°C。 东南偏东 风，风向多变。",
            "moonrise": "04:12",
            "moonset": "14:08",
            "moonPhrase": "残月",
            "rain": "2",
            "uvIndex": "6",
            "uvDescription": "强",
            "rain_pcpn": "0.0"
        },
        {
            "day": "26日（星期三）",
            "date": "2025-02-26",
            "week": "星期三",
            "wea": "阴转多云",
            "wea_img": "yun",
            "wea_day": "阴",
            "wea_day_img": "yin",
            "wea_night": "多云",
            "wea_night_img": "yun",
            "tem": "10",
            "tem1": "10",
            "tem2": "1",
            "humidity": "65%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:53",
            "sunset": "18:18",
            "air": "67",
            "air_level": "良",
            "air_tips": "",
            "phrase": "多云",
            "narrative": "阴。 最高 11°C。 西南 风，风向多变。",
            "moonrise": "05:01",
            "moonset": "15:15",
            "moonPhrase": "残月",
            "rain": "24",
            "uvIndex": "3",
            "uvDescription": "中等",
            "rain_pcpn": "0.0"
        },
        {
            "day": "27日（星期四）",
            "date": "2025-02-27",
            "week": "星期四",
            "wea": "多云转晴",
            "wea_img": "yun",
            "wea_day": "多云",
            "wea_day_img": "yun",
            "wea_night": "晴",
            "wea_night_img": "qing",
            "tem": "15",
            "tem1": "15",
            "tem2": "1",
            "humidity": "69%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:52",
            "sunset": "18:19",
            "air": "79",
            "air_level": "良",
            "air_tips": "",
            "phrase": "多云",
            "narrative": "阴。 最高 14°C。 东南偏南 风，风向多变。",
            "moonrise": "05:45",
            "moonset": "16:23",
            "moonPhrase": "残月",
            "rain": "15",
            "uvIndex": "3",
            "uvDescription": "中等",
            "rain_pcpn": "0.0"
        },
        {
            "day": "28日（星期五）",
            "date": "2025-02-28",
            "week": "星期五",
            "wea": "晴",
            "wea_img": "qing",
            "wea_day": "晴",
            "wea_day_img": "qing",
            "wea_night": "晴",
            "wea_night_img": "qing",
            "tem": "18",
            "tem1": "18",
            "tem2": "7",
            "humidity": "69%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:51",
            "sunset": "18:19",
            "air": "77",
            "air_level": "良",
            "air_tips": "",
            "phrase": "局部多云",
            "narrative": "少云。 最高 19°C。 南 风，风向多变。",
            "moonrise": "06:23",
            "moonset": "17:33",
            "moonPhrase": "残月",
            "rain": "11",
            "uvIndex": "6",
            "uvDescription": "强",
            "rain_pcpn": "0.0"
        },
        {
            "day": "01日（星期六）",
            "date": "2025-03-01",
            "week": "星期六",
            "wea": "多云",
            "wea_img": "yun",
            "wea_day": "多云",
            "wea_day_img": "yun",
            "wea_night": "多云",
            "wea_night_img": "yun",
            "tem": "25",
            "tem1": "25",
            "tem2": "12",
            "humidity": "71%",
            "visibility": "",
            "pressure": "",
            "win": [
                "无持续风向",
                "无持续风向"
            ],
            "win_speed": "<3级",
            "win_meter": "",
            "sunrise": "06:50",
            "sunset": "18:20",
            "air": "74",
            "air_level": "良",
            "air_tips": "",
            "phrase": "阵雨",
            "narrative": "阵雨。 最高 21°C。 东南偏东 风 10 到 15 每 km \/ h 。 降雨几率 40%。",
            "moonrise": "06:58",
            "moonset": "18:41",
            "moonPhrase": "新月",
            "rain": "39",
            "uvIndex": "6",
            "uvDescription": "强",
            "rain_pcpn": "0.0"
        }
    ],
    "nums": 0,
    "aqi": {
        "update_time": "00:16",
        "cityid": "101200101",
        "city": "武汉市",
        "cityEn": "",
        "country": "",
        "countryEn": "",
        "air": "100",
        "air_level": "良",
        "air_tips": "空气质量可接受，但某些污染物可能对极少数异常敏感人群健康有较弱影响。",
        "pm25": "75",
        "pm25_desc": "良",
        "pm10": "66",
        "pm10_desc": "良",
        "o3": "42",
        "o3_desc": "",
        "no2": "22",
        "no2_desc": "",
        "so2": "7",
        "so2_desc": "",
        "co": "0.7",
        "co_desc": "",
        "kouzhao": "不用佩戴口罩",
        "yundong": "适宜运动",
        "waichu": "不适宜外出",
        "kaichuang": "适宜开窗",
        "jinghuaqi": "不需要打开"
    }
}

# print(data["aqi"])
# print(data.get("aqi").get("waichu"))
# data.get("data")[2]["tem"] = 100
# print(data.get("data")[2].get("tem"))
# print(data.get("data")[2].get("humidity"))

# data_list= data.get("data")

# for i in data_list:
#     print(f"{i.get('day')} 天气状况：{i.get('wea')}, 平均温度{i.get('tem')}")

# 练习：打印每天大于0度的小时以及对应度数
data_list = data.get("data")

for dayDict in data_list:
    print(dayDict.get("day"))
    isEmpty = True
    for hourDict in dayDict.get("hours"):
        tem = int(hourDict.get("tem"))
        if tem > 1:
            isEmpty = False
            # print(hourDict.get("hours"), hourDict.get("tem"), sep=":", end="\t")
            print(f'{hourDict.get("hours")}({tem}度)', end="\t")
    if isEmpty:
        print("该天没有任何一个时刻大于1！", end="")
    print()
